<h1 style="text-align: center">
<div style="color: #DD3403; font-size: 60%">Data Science DISCOVERY MicroProject #1</div>
<span style="">MicroProject: United States Congress</span>
<div style="font-size: 60%;"><a href="https://discovery.cs.illinois.edu/microproject/01-us-congress/">https://discovery.cs.illinois.edu/microproject/01-us-congress/</a></div>
</h1>

<hr style="color: #DD3403;">

## Introduction

In this microproject, you will use Exploratory Data Analysis (EDA) techniques and the `groupby` function to find various statistics about the current legislators in the United States Congress.  Let's nerd out!

## Dataset: "congress-legislators"

The [@unitedstates project](https://theunitedstates.io/) maintains various high-quality datasets about the United States government.  Specifically, the `congress-legislators` dataset contains every member "of the United States Congress (1789-Present), congressional committees (1973-Present), committee membership (current only), and presidents and vice presidents of the United States in YAML, JSON, and CSV format."

The URL for the CSV dataset is:
```
https://theunitedstates.io/congress-legislators/legislators-current.csv
```

Load the dataset into a DataFrame called `df`:

In [10]:
import pandas as pd
df = pd.read_csv("https://theunitedstates.io/congress-legislators/legislators-current.csv")

<hr style="color: #DD3403;">

## Puzzle 1: Splitting The House of Representatives and The Senate

In this dataset, each row is one member of Congress.  The United States Congress is bicameral, being made up of both the House of Representatives and the Senate.  In the dataset:

- Representatives in the House of Representatives represent a district, which is encoded in the `district` column.  (Senators will have the `district` column blank.)
- Senators are elected for six years, with one-third of the senators up for election every two years.  The `senate_class` denotes which election class a senator is in.  (Representatives will have the `senate_class` column blank.)

Create two new DataFrames, `df_house` and `df_senate`, that contain members of the House of Representatives and the Senate:

In [11]:
df_house = df[df.district > -1]
df_house

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
27,Aderholt,Robert,B.,NaN,NaN,Robert B. Aderholt,1965-07-22,M,rep,AL,...,N00003028,NaN,H6AL04098,45516.0,400004,441.0,Robert B. Aderholt,NaN,29701.0,Robert Aderholt
30,Bilirakis,Gus,M.,NaN,NaN,Gus M. Bilirakis,1963-02-08,M,rep,FL,...,N00027462,NaN,H6FL09070,1022873.0,412250,17318.0,Gus M. Bilirakis,NaN,20758.0,Gus Bilirakis
31,Bishop,Sanford,D.,Jr.,NaN,"Sanford D. Bishop, Jr.",1947-02-04,M,rep,GA,...,N00002674,NaN,H2GA02031,26194.0,400030,26817.0,Sanford Bishop Jr.,NaN,29339.0,Sanford Bishop
33,Blumenauer,Earl,NaN,NaN,NaN,Earl Blumenauer,1948-08-16,M,rep,OR,...,N00007727,NaN,H6OR03064,43809.0,400033,367.0,Earl Blumenauer,NaN,29588.0,Earl Blumenauer
36,Buchanan,Vern,NaN,NaN,NaN,Vern Buchanan,1951-05-08,M,rep,FL,...,N00027626,NaN,H6FL13148,1021626.0,412196,66247.0,Vern Buchanan,NaN,20709.0,Vern Buchanan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,Kiggans,Jennifer,Ann,NaN,NaN,Jennifer Kiggans,1971-06-18,F,rep,VA,...,NaN,NaN,H2VA02064,NaN,456947,NaN,NaN,NaN,NaN,Jen Kiggans
535,Balint,Becca,A.,NaN,NaN,Becca Balint,1968-05-04,F,rep,VT,...,NaN,NaN,H2VT01076,NaN,456948,NaN,NaN,NaN,NaN,Becca Balint
536,Gluesenkamp Perez,Marie,NaN,NaN,NaN,Marie Gluesenkamp Perez,1988-06-06,F,rep,WA,...,NaN,NaN,H2WA03217,NaN,456949,NaN,Marie Gluesenkamp Perez,NaN,NaN,Marie Gluesenkamp Perez
537,Van Orden,Derrick,Francis,NaN,NaN,Derrick Van Orden,1969-09-15,M,rep,WI,...,NaN,NaN,H0WI03175,NaN,456950,NaN,Derrick Van Orden,NaN,NaN,Derrick Van Orden
538,Hageman,Harriet,Maxine,NaN,NaN,Harriet M. Hageman,1962-10-18,F,rep,WY,...,NaN,NaN,H2WY00166,NaN,456951,NaN,Harriet Hageman,NaN,NaN,Harriet Hageman

In [12]:
df_senate = df[df.type == 'sen']
df_senate

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
0,Brown,Sherrod,NaN,NaN,NaN,Sherrod Brown,1952-11-09,M,sen,OH,...,N00003535,S307,"H2OH13033,S6OH00163",5051.0,400050,27018.0,Sherrod Brown,NaN,29389.0,Sherrod Brown
1,Cantwell,Maria,NaN,NaN,NaN,Maria Cantwell,1958-10-13,F,sen,WA,...,N00007836,S275,"S8WA00194,H2WA01054",26137.0,300018,27122.0,Maria Cantwell,NaN,39310.0,Maria Cantwell
2,Cardin,Benjamin,L.,NaN,NaN,Benjamin L. Cardin,1943-10-05,M,sen,MD,...,N00001955,S308,"H6MD03177,S6MD03177",4004.0,400064,26888.0,Ben Cardin,NaN,15408.0,Ben Cardin
3,Carper,Thomas,Richard,NaN,NaN,Thomas R. Carper,1947-01-23,M,sen,DE,...,N00012508,S277,S8DE00079,663.0,300019,22421.0,Tom Carper,NaN,15015.0,Tom Carper
4,Casey,Robert,P.,Jr.,Bob,"Robert P. Casey, Jr.",1960-04-13,M,sen,PA,...,N00027503,S309,S6PA00217,47036.0,412246,2541.0,"Bob Casey, Jr.",NaN,40703.0,Bob Casey Jr.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,Britt,Katie,Elizabeth,NaN,NaN,Katie Boyd Britt,1982-02-02,F,sen,AL,...,NaN,S416,S2AL00145,NaN,456874,NaN,Katie Britt,NaN,NaN,Katie Britt
462,Schmitt,Eric,Stephen,NaN,NaN,Eric Schmitt,1975-06-20,M,sen,MO,...,NaN,S420,S2MO00544,NaN,456875,NaN,Eric Schmitt,NaN,NaN,Eric S. Schmitt
463,Vance,J.D. (James),(David),NaN,NaN,J.D. Vance,1984-08-02,M,sen,OH,...,NaN,S421,S2OH00436,NaN,456876,NaN,J.D. Vance,NaN,NaN,J. D. Vance
464,Fetterman,John,Karl,NaN,NaN,John Fetterman,1969-08-15,M,sen,PA,...,NaN,S418,S6PA00274,NaN,456877,166286.0,John Fetterman,NaN,NaN,John Fetterman
539,Ricketts,Pete,NaN,NaN,NaN,Pete Ricketts,1964-08-19,M,sen,NE,...,NaN,S423,S6NE00129,61233.0,456952,57777.0,Pete Ricketts,NaN,NaN,Pete Ricketts

<hr style="color: #DD3403;">

## Puzzle 2: Find the Controlling Party of the House of Representatives

In each body of Congress, the "controlling party" is the party that has the majority of the members.  Using `groupby`, create a DataFrame `df_house_party` that counts the number of members in each political party in the House of Representatives:

In [13]:
df_house_party = df_house.groupby("party").agg("count").reset_index()
df_house_party

,party,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
0,Democrat,215,215,112,9,9,215,215,215,215,...,181,0,215,123,215,165,171,0,161,215
1,Republican,225,225,119,8,13,225,225,225,225,...,184,0,225,108,225,155,169,0,135,222

### Puzzle 2 Analysis: How many Democrats and Republicans in the House?

Using the result above, fill out the following cell with the number of Democrats and Republications:

In [14]:
democrats_in_house = 215
republicans_in_house = 225

<hr style="color: #DD3403;">

## Puzzle 3: Find the Youngest Member of each Party in the House of Representatives

In the House of Representatives, who is the youngest member Democrat and who is the youngest Republican?

In [15]:
# For the Democrat:
birth_Demo = df_house[df_house.party == "Democrat"]["birthday"].max()
guy_Demo = df_house[(df_house.party == "Democrat") & (df_house.birthday == birth_Demo)]
print("The youngest person in the Democrat is")
print(guy_Demo.full_name)

The youngest person in the Democrat is
477    Maxwell Frost
Name: full_name, dtype: object

In [16]:
# For the Republican:
birth_Repu = df_house[df_house.party == "Republican"]["birthday"].max()
guy_Repu = df_house[(df_house.party == "Republican") & (df_house.birthday == birth_Repu)]
print("The youngest person in the Republican is")
print(guy_Repu.full_name)

The youngest person in the Republican is
478    Anna Paulina Luna
Name: full_name, dtype: object

### Puzzle 3 Analysis: How many Democrats and Republicans in the House?

Using the result above, provide the **full name** of the youngest Democrat and Republican:

In [17]:
youngest_democrat_in_house = "Maxwell Frost"
youngest_republican_in_house = "Anna Paulina Luna"

<hr style="color: #DD3403;">

## 🔬 Microproject Checkpoint Tests 🔬

In [18]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for the microproject.
# - If this cell runs without any error in the output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cells, make changes, and RE-RUN your code and then this cell.

tada = "\N{PARTY POPPER}"
R = df[ df.party == "Republican" ].head(1).index[0]
D = df[ df.party == "Democrat" ].head(1).index[0]

assert( len(df) > 500 )
assert( len(df_senate) <= 100 )
assert( len(df_house) == len(df) - len(df_senate) )
print(f"{tada} Puzzle 1: All Tests Passed! {tada}")

assert(len(df_house_party) == 2)
assert((df_house_party.index[0] == "Democrat" or df_house_party.index[0] == "Republican" or "party" in df.columns.tolist()))
assert(len(df) - len(df_senate) - df_house.value_counts(df.columns.tolist()[12])[df.sort_values(df.columns.tolist()[6]).iloc[R][df.columns.tolist()[12]]] == democrats_in_house)
assert(len(df) - len(df_senate) - df_house.value_counts(df.columns.tolist()[12])[df.sort_values(df.columns.tolist()[6]).iloc[D][df.columns.tolist()[12]]] == republicans_in_house)
print(f"{tada} Puzzle 2: All Tests Passed! {tada}")

assert(df[ df.party == "Democrat" ].sort_values(df.columns.tolist()[6]).tail(1).values[0][5] == youngest_democrat_in_house)
assert(df[ df.party == "Republican" ].sort_values(df.columns.tolist()[6]).tail(1).values[0][5] == youngest_republican_in_house)
print(f"{tada} Puzzle 3: All Tests Passed! {tada}")

print(f"{tada}{tada} All Tests Passed! {tada}{tada}")

🎉 Puzzle 1: All Tests Passed! 🎉
🎉 Puzzle 2: All Tests Passed! 🎉
🎉 Puzzle 3: All Tests Passed! 🎉
🎉🎉 All Tests Passed! 🎉🎉

<hr style="color: #DD3403;">

## Submission

You're almost done!  All you need to do is to commit your lab to GitHub and run the GitHub Actions Grader:

1.  ⚠️ **Make certain to save your work.** ⚠️ To do this, go to **File => Save All**

2.  After you have saved, exit this notebook and follow the instructions to commit and grade this MicroProject!